<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\MarketingCampaign;

class MarketingCampaignCsvSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $campaigns = [
            ['campaign_code' => '537', 'name' => 'Dziminska Doractwo SP proste (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '538', 'name' => 'Dziminska Doractwo P proste (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '539', 'name' => 'Dziminska Doractwo SP zdjecia (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '540', 'name' => 'Dziminska Doractwo P zdjecia (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '541', 'name' => 'Dziminska Doractwo SP (strona sprzedazowa)', 'source_type' => 'website'],
            ['campaign_code' => '542', 'name' => 'Geogebra SP (strona sprzedazowa)', 'source_type' => 'website'],
            ['campaign_code' => '543', 'name' => 'Dziminska Doractwo SP zdjecia z napisami (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '544', 'name' => 'Dziminska Doractwo P zdjecia z napisami (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '545', 'name' => 'Szkolenie TIK 15.10', 'source_type' => 'training'],
            ['campaign_code' => '546', 'name' => 'Waldemar Canva SP proste (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '547', 'name' => 'Waldemar Canva P proste (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '548', 'name' => 'Waldemar Canva SP zdjecia (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '549', 'name' => 'Waldemar Canva P zdjecia (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '550', 'name' => 'Waldemar Canva SP (strona sprzedazowa)', 'source_type' => 'website'],
            ['campaign_code' => '551', 'name' => 'Lorens działalność (strona sprzedazowa)', 'source_type' => 'website'],
            ['campaign_code' => '552', 'name' => 'Lorens działalność różne SP (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '553', 'name' => 'Lorens działalność różne P (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '554', 'name' => '"Działalność i protokołowanie rad ...2024-10-29" [Lorens Roman] E-mail do szkół z wykazu RSPO - 23700 osób (wys. 2024-10-21 10:20)', 'source_type' => 'email'],
            ['campaign_code' => '555', 'name' => '"Działalność i protokołowanie rad ...2024-10-29" [Lorens Roman] E-mail do dyrektorów -643 osoby, którzy już korzystali z naszych szkoleń (wys. 2024-10-21 11:30)', 'source_type' => 'email'],
            ['campaign_code' => '556', 'name' => 'Darmowe szkolenie Lorensa Praw i obowiązki dyrektora - reklama fb', 'source_type' => 'facebook'],
            ['campaign_code' => '557', 'name' => 'Szkolenie TIK 22.10 Canva', 'source_type' => 'training'],
            ['campaign_code' => '558', 'name' => 'Marciniak WOPFU SP proste (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '559', 'name' => 'Marciniak WOPFU P proste (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '560', 'name' => 'Marciniak WOPFU SP zdjecia (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '561', 'name' => 'Marciniak WOPFU P zdjecia (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '562', 'name' => 'Marciniak WOPFU SP (strona sprzedazowa)', 'source_type' => 'website'],
            ['campaign_code' => '563', 'name' => 'Darmowe szkolenie Lorensa Praw i obowiązki dyrektora - reklama fb V2', 'source_type' => 'facebook'],
            ['campaign_code' => '564', 'name' => 'Darmowe szkolenie Lorensa Praw i obowiązki dyrektora - reklama fb FILM', 'source_type' => 'facebook'],
            ['campaign_code' => '565', 'name' => 'Geogebra produkt (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '566', 'name' => 'Geogebra SP (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '567', 'name' => 'Geogebra SP (reklama) V2', 'source_type' => 'facebook'],
            ['campaign_code' => '568', 'name' => 'Gegebra SP (Strona sprzedażowa)', 'source_type' => 'website'],
            ['campaign_code' => '569', 'name' => 'Gegebra SP (Strona sprzedażowa) V2', 'source_type' => 'website'],
            ['campaign_code' => '570', 'name' => 'Dziminska Doractwo SP proste (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '571', 'name' => 'Dziminska Doractwo P proste (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '572', 'name' => 'Dziminska Doractwo SP zdjecia (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '573', 'name' => 'Dziminska Doractwo P zdjecia (reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '574', 'name' => 'Dziminska Doractwo SP zdjecia (reklama) V2', 'source_type' => 'facebook'],
            ['campaign_code' => '575', 'name' => 'Dziminska Doractwo SP (strona sprzedazowa)', 'source_type' => 'website'],
            ['campaign_code' => '576', 'name' => 'Dziminska Doractwo SP (strona sprzedazowa) V2', 'source_type' => 'website'],
            ['campaign_code' => '577', 'name' => 'E-mail podczas wtorkowego przypomnienia o webinarze 2024-10-22', 'source_type' => 'email'],
            ['campaign_code' => '578', 'name' => 'Kuropatwa Kontrola rozne SP (Reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '579', 'name' => 'Kuropatwa Kontrola rozne P (Reklama)', 'source_type' => 'facebook'],
            ['campaign_code' => '580', 'name' => 'Kuropatwa Kontrola (Strona sprzedazowa)', 'source_type' => 'website'],
            ['campaign_code' => '581', 'name' => 'E-mail do szkół z wykazu RSPO - 23700 osób (wys. 2024-10-24 09:30)', 'source_type' => 'email'],
            ['campaign_code' => '582', 'name' => 'E-mail do szkół z wykazu RSPO - 23700 osób (wys. 2024-10-25 08:10)', 'source_type' => 'email'],
            ['campaign_code' => '583', 'name' => 'Szkolenie TIK 29.10 AI', 'source_type' => 'training'],
            ['campaign_code' => '584', 'name' => 'Szkoelnie TIK 5.11 Canva', 'source_type' => 'training'],
            ['campaign_code' => '585', 'name' => 'Bezpłatne wydarzenie na FB (2021-11-06)', 'source_type' => 'facebook'],
            ['campaign_code' => '586', 'name' => 'Bezpłatny POST na FB', 'source_type' => 'facebook'],
            ['campaign_code' => '587', 'name' => 'E-mail do szkół RSPO - 2024-11-06', 'source_type' => 'email'],
            ['campaign_code' => '588', 'name' => 'Prawa i obowiązki Lorens 1', 'source_type' => 'facebook'],
            ['campaign_code' => '589', 'name' => 'Prawa i obowiązki Lorens 2', 'source_type' => 'facebook'],
            ['campaign_code' => '590', 'name' => 'Prawa i obowiązki Lorens 3', 'source_type' => 'facebook'],
            ['campaign_code' => '591', 'name' => 'Prawa i obowiązki Lorens 3 SP', 'source_type' => 'facebook'],
            ['campaign_code' => '592', 'name' => 'TIK 12.11.2024', 'source_type' => 'training'],
            ['campaign_code' => '593', 'name' => 'email z informacją o webinarze', 'source_type' => 'email'],
            ['campaign_code' => '594', 'name' => 'email do RSPO z awaryjnego formularza 2024-11-12 14:00', 'source_type' => 'email'],
            ['campaign_code' => '595', 'name' => 'email do grupy dyrektorzy z awaryjnego formularza 2024-11-12 14:00', 'source_type' => 'email'],
            ['campaign_code' => '596', 'name' => 'email do tych co byli na dotychczasowych szkoleniach Lorensa 2024-11-12 16:00', 'source_type' => 'email'],
            ['campaign_code' => '597', 'name' => 'email do 2024-11-13 11:00 - dzień przed szkoleniem temat: Zyskaj pewność w kontaktach z rodzicami i prawo po swojej stronie – szkolenie z Romanem Lorensem (Ostatni dzień zapisów!)', 'source_type' => 'email'],
            ['campaign_code' => '598', 'name' => 'email do RSPO z awaryjnego formularza 2024-11-14 10:50', 'source_type' => 'email'],
            ['campaign_code' => '599', 'name' => 'Dziminska reklama 1', 'source_type' => 'facebook'],
            ['campaign_code' => '600', 'name' => 'Dziminska reklama 2', 'source_type' => 'facebook'],
            ['campaign_code' => '601', 'name' => 'Dziminska reklama 3', 'source_type' => 'facebook'],
            ['campaign_code' => '602', 'name' => 'Dziminska reklama 4', 'source_type' => 'facebook'],
            ['campaign_code' => '603', 'name' => 'Dziminska reklama 5', 'source_type' => 'facebook'],
            ['campaign_code' => '604', 'name' => 'Dziminska reklama SP', 'source_type' => 'facebook'],
            ['campaign_code' => '605', 'name' => 'Geogebra remarketing 1 przejście do kasy', 'source_type' => 'remarketing'],
            ['campaign_code' => '606', 'name' => 'Doradztwo remarketing 1 przejście do kasy', 'source_type' => 'remarketing'],
            ['campaign_code' => '607', 'name' => 'Geogebra remarketing 2 przejście do kasy', 'source_type' => 'remarketing'],
            ['campaign_code' => '608', 'name' => 'Doradztwo remarketing 2 przejście do kasy', 'source_type' => 'remarketing'],
            ['campaign_code' => '609', 'name' => 'Geogebra remarketing 1 emaile', 'source_type' => 'remarketing'],
            ['campaign_code' => '610', 'name' => 'Doradztwo remarketing 1 emaile', 'source_type' => 'remarketing'],
            ['campaign_code' => '611', 'name' => 'Geogebra remarketing 2 emaile', 'source_type' => 'remarketing'],
            ['campaign_code' => '612', 'name' => 'Doradztwo remarketing 2 emaile', 'source_type' => 'remarketing'],
            ['campaign_code' => '613', 'name' => 'email do RSPO z awaryjnego formularza 2024-11-18 12:50', 'source_type' => 'email'],
            ['campaign_code' => '614', 'name' => 'Darmowe lorensa grafika', 'source_type' => 'facebook'],
            ['campaign_code' => '615', 'name' => 'Darmowe lorensa film', 'source_type' => 'facebook'],
            ['campaign_code' => '616', 'name' => 'Darmowe lorensa short', 'source_type' => 'facebook'],
            ['campaign_code' => '617', 'name' => 'Dziminska Doradztwo 27.11.2024 Nowi #1', 'source_type' => 'facebook'],
            ['campaign_code' => '618', 'name' => 'Dziminska Doradztwo 27.11.2024 Nowi #2', 'source_type' => 'facebook'],
            ['campaign_code' => '619', 'name' => 'Dziminska Doradztwo 27.11.2024 Nowi #3', 'source_type' => 'facebook'],
            ['campaign_code' => '620', 'name' => 'Dziminska Doradztwo 27.11.2024 Remarketing #1', 'source_type' => 'remarketing'],
            ['campaign_code' => '621', 'name' => 'Dziminska Doradztwo 27.11.2024 Remarketing #2', 'source_type' => 'remarketing'],
            ['campaign_code' => '622', 'name' => 'Dziminska Doradztwo 27.11.2024 Remarketing #3', 'source_type' => 'remarketing'],
            ['campaign_code' => '623', 'name' => 'E-mail z zaświadczeniem 24-1-2024', 'source_type' => 'email'],
            ['campaign_code' => '624', 'name' => 'Reklama tik 26.11 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '625', 'name' => 'Reklama tik 26.11 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '626', 'name' => 'Reklama tik 26.11 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '627', 'name' => 'Lorens email do DYREKTORÓW 2024-11-25 14:00', 'source_type' => 'email'],
            ['campaign_code' => '628', 'name' => 'Lorens email do RSPO 2024-11-25 08:15', 'source_type' => 'email'],
            ['campaign_code' => '629', 'name' => 'Dzimińska e-mail 2024-11-26 Dyrektorzy', 'source_type' => 'email'],
            ['campaign_code' => '630', 'name' => 'Lorensa Relacje Organu #1', 'source_type' => 'facebook'],
            ['campaign_code' => '631', 'name' => 'Lorensa Relacje Organu #2', 'source_type' => 'facebook'],
            ['campaign_code' => '632', 'name' => 'Lorensa Relacje Organu Film #3', 'source_type' => 'facebook'],
            ['campaign_code' => '633', 'name' => 'Lorensa Relacje Organu Film z napisami #4', 'source_type' => 'facebook'],
            ['campaign_code' => '634', 'name' => 'E-mail z zaświadczeniem 2024-12-01', 'source_type' => 'email'],
            ['campaign_code' => '635', 'name' => 'Reklama tik 03.12 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '636', 'name' => 'Reklama tik 03.12 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '637', 'name' => 'Reklama tik 03.12 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '638', 'name' => 'Marciniak Rola #1', 'source_type' => 'facebook'],
            ['campaign_code' => '639', 'name' => 'Marciciak Rola #2', 'source_type' => 'facebook'],
            ['campaign_code' => '640', 'name' => 'Lorens email do RSPO 2024-11-25 08:15', 'source_type' => 'email'],
            ['campaign_code' => '641', 'name' => 'Lorens Odpowiedzialność QR', 'source_type' => 'facebook'],
            ['campaign_code' => '642', 'name' => 'Lorens Odpowiedzialność 1', 'source_type' => 'facebook'],
            ['campaign_code' => '643', 'name' => 'Lorens Odpowiedzialność 2', 'source_type' => 'facebook'],
            ['campaign_code' => '644', 'name' => 'Lorens Odpowiedzialność 3', 'source_type' => 'facebook'],
            ['campaign_code' => '645', 'name' => 'Wojkowska Konkurs QR', 'source_type' => 'facebook'],
            ['campaign_code' => '646', 'name' => 'Wojkowska Konkurs 1', 'source_type' => 'facebook'],
            ['campaign_code' => '647', 'name' => 'Wojkowska Konkurs 2', 'source_type' => 'facebook'],
            ['campaign_code' => '648', 'name' => 'Wojkowska Konkurs 3', 'source_type' => 'facebook'],
            ['campaign_code' => '649', 'name' => 'Marciniak Rola #3', 'source_type' => 'facebook'],
            ['campaign_code' => '650', 'name' => 'Marciniak Rola #4', 'source_type' => 'facebook'],
            ['campaign_code' => '651', 'name' => 'Lorens Odpowiedzialność 4', 'source_type' => 'facebook'],
            ['campaign_code' => '652', 'name' => 'Lorens Odpowiedzialność 5', 'source_type' => 'facebook'],
            ['campaign_code' => '653', 'name' => 'Wojkowska Konkurs 4', 'source_type' => 'facebook'],
            ['campaign_code' => '654', 'name' => 'Wojkowska Konkurs 5', 'source_type' => 'facebook'],
            ['campaign_code' => '655', 'name' => 'Reklama tik 12.12 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '656', 'name' => 'Reklama tik 12.12 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '657', 'name' => 'Reklama tik 12.12 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '658', 'name' => 'Wojkowska Konkurs #6', 'source_type' => 'facebook'],
            ['campaign_code' => '659', 'name' => 'Reklama TIK 17.12 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '660', 'name' => 'Reklama TIK 17.12 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '661', 'name' => 'Reklama TIK 17.12 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '662', 'name' => 'Lorens podsumowanie #1', 'source_type' => 'facebook'],
            ['campaign_code' => '663', 'name' => 'Lorens podsumowanie #5 2', 'source_type' => 'facebook'],
            ['campaign_code' => '664', 'name' => 'Lorens podsumowanie #6 3', 'source_type' => 'facebook'],
            ['campaign_code' => '665', 'name' => 'Lorens podsumowanie #4', 'source_type' => 'facebook'],
            ['campaign_code' => '666', 'name' => 'GeoGebra 23.01.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '667', 'name' => 'GeoGebra 23.01.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '668', 'name' => 'GeoGebra 23.01.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '669', 'name' => 'Dzimińska e-mail 2025-01-09 RSPO', 'source_type' => 'email'],
            ['campaign_code' => '670', 'name' => 'Dzimińska 15.01.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '671', 'name' => 'Dzimińska 15.01.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '672', 'name' => 'Dzimińska 15.01.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '673', 'name' => 'Wojkowska 27.01.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '674', 'name' => 'Wojkowska 27.01.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '675', 'name' => 'TIK 14.01.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '676', 'name' => 'TIK 14.01.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '677', 'name' => 'TIK 14.01.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '678', 'name' => 'Zwykły podst na FB', 'source_type' => 'facebook'],
            ['campaign_code' => '679', 'name' => 'Zwykłe wydarzenie na FB', 'source_type' => 'facebook'],
            ['campaign_code' => '680', 'name' => 'Lorens email do RSPO 2025-01-14 12:30', 'source_type' => 'email'],
            ['campaign_code' => '681', 'name' => 'Lorens - email z przypomnieniem o wtorkowym webinarze 2025-01-14 17:30', 'source_type' => 'email'],
            ['campaign_code' => '682', 'name' => 'Wydarzenie na FB dodane 2025-01-15', 'source_type' => 'facebook'],
            ['campaign_code' => '683', 'name' => 'Lorens zasady 28.01.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '684', 'name' => 'Lorens zasady 28.01.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '685', 'name' => 'Lorens zasady 28.01.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '686', 'name' => 'Lorens zasady 28.01.2025 #4', 'source_type' => 'facebook'],
            ['campaign_code' => '687', 'name' => 'Marciniak QRcode na FB', 'source_type' => 'facebook'],
            ['campaign_code' => '688', 'name' => 'Marciniak -  Wydarzenie na FB dodane 2025-01-15', 'source_type' => 'facebook'],
            ['campaign_code' => '689', 'name' => 'Lorens - e-mail do byłych uczestników i do RSPO', 'source_type' => 'email'],
            ['campaign_code' => '690', 'name' => 'Marician Komunikować 29.01.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '691', 'name' => 'Marician Komunikować 29.01.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '692', 'name' => 'Marician Komunikować 29.01.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '693', 'name' => 'Marciniak - e-mail do byłych uczestników i do RSPO', 'source_type' => 'email'],
            ['campaign_code' => '694', 'name' => 'Lorens - e-mail 2025-01-27 08:15 do byłych uczestników i do RSPO', 'source_type' => 'email'],
            ['campaign_code' => '695', 'name' => 'E-mail z zaświadczeniami 2025-01-26 21;16', 'source_type' => 'email'],
            ['campaign_code' => '696', 'name' => 'Marciniak - e-mail 2025-01-27 10:35 do byłych uczestników i do RSPO', 'source_type' => 'email'],
            ['campaign_code' => '697', 'name' => 'Post z nowym filmem Romana Lorens 2025-01-27 10:00', 'source_type' => 'facebook'],
            ['campaign_code' => '698', 'name' => 'Lorens zasady 28.01.2025 #5', 'source_type' => 'facebook'],
            ['campaign_code' => '699', 'name' => 'TIK 28.01.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '700', 'name' => 'TIK 28.01.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '701', 'name' => 'TIK 28.01.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '702', 'name' => 'TIK 28.01.2025 #4', 'source_type' => 'facebook'],
            ['campaign_code' => '703', 'name' => 'Lorens - email z przypomnieniem o wtorkowym webinarze 2025-01-28 17:30', 'source_type' => 'email'],
            ['campaign_code' => '704', 'name' => 'Lorens - email z przypomnieniem o wtorkowym webinarze 2025-01-28 17:30', 'source_type' => 'email'],
            ['campaign_code' => '705', 'name' => 'Lorens Działalność 07.02.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '706', 'name' => 'Lorens Działalność 07.02.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '707', 'name' => 'Lorens Działalność 07.02.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '708', 'name' => 'Lorens - e-mail 2025-01-31 10:55 do byłych uczestników i do RSPO', 'source_type' => 'email'],
            ['campaign_code' => '709', 'name' => 'Lorens - e-mail z zaświadczeniami 2025-02-01 18:57', 'source_type' => 'email'],
            ['campaign_code' => '710', 'name' => 'Lorens - e-mail 2025-02-03 09:30 do byłych uczestników i do RSPO', 'source_type' => 'email'],
            ['campaign_code' => '711', 'name' => 'Lorens Działalność 07.02.2025 #4', 'source_type' => 'facebook'],
            ['campaign_code' => '712', 'name' => 'TIK 07.02.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '713', 'name' => 'TIK 07.02.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '714', 'name' => 'TIK 07.02.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '715', 'name' => 'TIK 07.02.2025 #4', 'source_type' => 'facebook'],
            ['campaign_code' => '716', 'name' => 'Lorens - e-mail 2025-02-05 09:30 do byłych uczestników i do RSPO', 'source_type' => 'email'],
            ['campaign_code' => '717', 'name' => 'Wojkowska - Konkurs na dyrektora - wydarzenie na FB 2024-02-04 16-20', 'source_type' => 'facebook'],
            ['campaign_code' => '718', 'name' => 'E-mail przed webinarem 2025-02-04 17:30', 'source_type' => 'email'],
            ['campaign_code' => '719', 'name' => 'E-mail RSPO dzień przed szkoleniem 2025-02-06 10:30', 'source_type' => 'email'],
            ['campaign_code' => '720', 'name' => 'Wojkowska Konkurs 13.02.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '721', 'name' => 'Wojkowska Konkurs 13.02.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '722', 'name' => 'Wojkowska Konkurs 13.02.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '723', 'name' => 'Wojkowska SIO - wydarzenie na FB', 'source_type' => 'facebook'],
            ['campaign_code' => '724', 'name' => 'Wojkowska SIO - email do RSPO i Ci co się u nas już szkolili', 'source_type' => 'email'],
            ['campaign_code' => '725', 'name' => 'Wojkowska - email w dniu webinaru TIK 2025-02-11 (wtorek)', 'source_type' => 'email'],
            ['campaign_code' => '726', 'name' => 'Wojkowska System 17.02.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '727', 'name' => 'Wojkowska System 17.02.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '728', 'name' => 'Wojkowska System 17.02.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '729', 'name' => 'Wojkowska System 17.02.2025 #4', 'source_type' => 'facebook'],
            ['campaign_code' => '730', 'name' => 'Wojkowska System 17.02.2025 #5 NOWY LP', 'source_type' => 'facebook'],
            ['campaign_code' => '731', 'name' => 'Wojkowska Konkurs 13.02.2025 #4  NOWY LP', 'source_type' => 'facebook'],
            ['campaign_code' => '732', 'name' => 'Lorens Standardy - wydarzenie na FB', 'source_type' => 'facebook'],
            ['campaign_code' => '733', 'name' => 'Lorens Standardy 26.02.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '734', 'name' => 'Lorens Standardy 26.02.2025 #1 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '735', 'name' => 'Lorens Standardy 26.02.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '736', 'name' => 'Lorens Standardy 26.02.2025 #2 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '737', 'name' => 'Lorens 26.02.2025 - e-mail z zaświadczeniami 2025-02-17', 'source_type' => 'email'],
            ['campaign_code' => '738', 'name' => 'Lorens Standardy 26.02.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '739', 'name' => 'Lorens Standardy 26.02.2025 #3 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '740', 'name' => 'TIK 18.02.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '741', 'name' => 'TIK 18.02.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '742', 'name' => 'Lorens Standardy 26.02.2025 #4', 'source_type' => 'facebook'],
            ['campaign_code' => '743', 'name' => 'Lorens Standardy 26.02.2025 #4 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '744', 'name' => 'Dziminska Doradztwo 17.02.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '745', 'name' => 'Dziminska Doradztwo 17.02.2025 #1 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '746', 'name' => 'Dziminska Doradztwo 17.02.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '747', 'name' => 'Dziminska Doradztwo 17.02.2025 #2 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '748', 'name' => 'Lorens e-mail do RSPO 2025-02-19', 'source_type' => 'email'],
            ['campaign_code' => '749', 'name' => 'Dzimińska - Doradztwo e-mail do RSPO 2025-02-19', 'source_type' => 'email'],
            ['campaign_code' => '750', 'name' => 'Lorens Standardy 26.02.2025 #3 V2 Linki też na górze', 'source_type' => 'facebook'],
            ['campaign_code' => '751', 'name' => 'Lorens Standardy 26.02.2025 #4 V2 Linki też na górze', 'source_type' => 'facebook'],
            ['campaign_code' => '752', 'name' => 'Dzimińska - Doradztwo e-mail do RSPO 2025-02-24', 'source_type' => 'email'],
            ['campaign_code' => '753', 'name' => 'Lorens e-mail do RSPO 2025-02-24', 'source_type' => 'email'],
            ['campaign_code' => '754', 'name' => 'E-mail z zapowiedzą wtorkowego webinaru o Canva. 2025-02-24 19:00', 'source_type' => 'email'],
            ['campaign_code' => '755', 'name' => 'TIK 25.02.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '756', 'name' => 'TIK 25.02.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '757', 'name' => 'TIK 25.02.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '758', 'name' => 'E-mail z zapowiedzą wtorkowego webinaru o Canva. 2025-02-25 10:15', 'source_type' => 'email'],
            ['campaign_code' => '759', 'name' => 'E-mail do RSPO Wojkowska SIO 2025-02-27 08:15', 'source_type' => 'email'],
            ['campaign_code' => '760', 'name' => 'Wojkowska System 6.03.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '761', 'name' => 'Wojkowska System 6.03.2025 #1 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '762', 'name' => 'Wojkowska System 6.03.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '763', 'name' => 'Wojkowska System 6.03.2025 #2 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '764', 'name' => 'Wojkowska Konkurs 11.03.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '765', 'name' => 'Wojkowska Konkurs 11.03.2025 #1 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '766', 'name' => 'Wojkowska Konkurs 11.03.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '767', 'name' => 'Wojkowska Konkurs 11.03.2025 #2 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '768', 'name' => 'Wojkowska - Konkurs na dyrektora - e-mail RSPO 2025-02-28', 'source_type' => 'email'],
            ['campaign_code' => '769', 'name' => 'Dziminska Doractwo kod QR', 'source_type' => 'facebook'],
            ['campaign_code' => '770', 'name' => 'Niedzielny e-mail o wtorkowym webinarze 2025-03-02 18:45', 'source_type' => 'email'],
            ['campaign_code' => '771', 'name' => 'E-mail do RSPO Wojkowska SIO 2025-03-03 11:15', 'source_type' => 'email'],
            ['campaign_code' => '772', 'name' => 'TIK 04.03.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '773', 'name' => 'TIK 04.03.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '774', 'name' => 'TIK 04.03.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '775', 'name' => 'Dziminska Doradztwo 12.03.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '776', 'name' => 'Dziminska Doradztwo 12.03.2025 #1 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '777', 'name' => 'Dziminska Doradztwo 12.03.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '778', 'name' => 'Dziminska Doradztwo 12.03.2025 #2 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '779', 'name' => 'Lorens - e-mail: RSPO i kursanci 2025-03-07 12:45', 'source_type' => 'email'],
            ['campaign_code' => '780', 'name' => 'Lorens Arkusz 13.03.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '781', 'name' => 'Lorens Arkusz 13.03.2025 #1 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '782', 'name' => 'Lorens Arkusz 13.03.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '783', 'name' => 'Lorens Arkusz 13.03.2025 #2 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '784', 'name' => 'Lorens Arkusz 13.03.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '785', 'name' => 'Lorens Arkusz 13.03.2025 #3 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '786', 'name' => 'Lorens Arkusz QR 24.03', 'source_type' => 'facebook'],
            ['campaign_code' => '787', 'name' => 'Lorens Arkusz 24.03.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '788', 'name' => 'Lorens Arkusz 24.03.2025 #1 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '789', 'name' => 'Lorens Arkusz 24.03.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '790', 'name' => 'Lorens Arkusz 24.03.2025 #2 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '791', 'name' => 'Lorens Arkusz 24.03.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '792', 'name' => 'Lorens Arkusz 24.03.2025 #3 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '793', 'name' => 'Niedzielny e-mail o webinarze: Wordwall 2025-03-06', 'source_type' => 'email'],
            ['campaign_code' => '794', 'name' => 'Lorens - email do RSPO i kursantów 2025-03-17 13:15', 'source_type' => 'email'],
            ['campaign_code' => '795', 'name' => 'Lorens wydarzenie FB 2025-03-18', 'source_type' => 'facebook'],
            ['campaign_code' => '796', 'name' => 'Narzędzia Doradztwa - Donata Dzimińska do RSPO 2025-03-19', 'source_type' => 'email'],
            ['campaign_code' => '797', 'name' => 'Lorens Arkusz 24.03.2025 #4', 'source_type' => 'facebook'],
            ['campaign_code' => '798', 'name' => 'Lorens Arkusz 24.03.2025 #4 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '799', 'name' => 'Dziminska Doradztwo 26.03.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '800', 'name' => 'Dziminska Doradztwo 26.03.2025 #1 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '801', 'name' => 'Dziminska Doradztwo 26.03.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '802', 'name' => 'Dziminska Doradztwo 26.03.2025 #2 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '803', 'name' => 'Lorens Statut 27.03.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '804', 'name' => 'Lorens Statut 27.03.2025 #1 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '805', 'name' => 'Lorens Statut 27.03.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '806', 'name' => 'Lorens Statut 27.03.2025 #2 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '807', 'name' => 'Lorens Statut 27.03.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '808', 'name' => 'Lorens Statut 27.03.2025 #3 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '809', 'name' => 'Kącik Geogebra 27.03.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '810', 'name' => 'Kącik Geogebra 27.03.2025 #1 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '811', 'name' => 'Kącik Geogebra 27.03.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '812', 'name' => 'Kącik Geogebra 27.03.2025 #2 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '813', 'name' => 'Reklama TIK 25.03 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '814', 'name' => 'Reklama TIK 25.03 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '815', 'name' => 'Lorens Konkurs dyrektora QR 09.04', 'source_type' => 'facebook'],
            ['campaign_code' => '816', 'name' => 'Lorens Awans zawodowy QR 15.05', 'source_type' => 'facebook'],
            ['campaign_code' => '817', 'name' => 'Lorens Konkurs Dyrektora 09.04.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '818', 'name' => 'Lorens Konkurs Dyrektora 09.04.2025 #1 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '819', 'name' => 'Lorens Konkurs Dyrektora 09.04.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '820', 'name' => 'Lorens Konkurs Dyrektora 09.04.2025 #2 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '821', 'name' => 'Lorens Konkurs Dyrektora 09.04.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '822', 'name' => 'Lorens Konkurs Dyrektora 09.04.2025 #3 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '823', 'name' => 'Lorens Konkurs Dyrektora 09.04.2025 #4', 'source_type' => 'facebook'],
            ['campaign_code' => '824', 'name' => 'Lorens Konkurs Dyrektora 09.04.2025 #4 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '825', 'name' => 'Lorens Awans Zawodowy 15.04.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '826', 'name' => 'Lorens Awans Zawodowy 15.04.2025 #1 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '827', 'name' => 'Lorens Awans Zawodowy 15.04.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '828', 'name' => 'Lorens Awans Zawodowy 15.04.2025 #2 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '829', 'name' => 'Lorens Awans Zawodowy 15.04.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '830', 'name' => 'Lorens Awans Zawodowy 15.04.2025 #3 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '831', 'name' => 'Lorens Awans Zawodowy 15.04.2025 #4', 'source_type' => 'facebook'],
            ['campaign_code' => '832', 'name' => 'Lorens Awans Zawodowy 15.04.2025 #4 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '833', 'name' => 'Reklama TIK 01.04 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '834', 'name' => 'Reklama TIK 01.04 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '835', 'name' => 'Reklama TIK 01.04 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '836', 'name' => 'Lorens czas pracy QR', 'source_type' => 'facebook'],
            ['campaign_code' => '837', 'name' => 'Lorens Czas Pracy 10.04.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '838', 'name' => 'Lorens Czas Pracy 10.04.2025 #1 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '839', 'name' => 'Lorens Czas Pracy 10.04.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '840', 'name' => 'Lorens Czas Pracy 10.04.2025 #2 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '841', 'name' => 'Lorens Czas Pracy 10.04.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '842', 'name' => 'Lorens Czas Pracy 10.04.2025 #3 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '843', 'name' => 'Lorens Czas Pracy 10.04.2025 #4', 'source_type' => 'facebook'],
            ['campaign_code' => '844', 'name' => 'Lorens Czas Pracy 10.04.2025 #4 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '845', 'name' => 'Reklama TIK 08.04 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '846', 'name' => 'Reklama TIK 08.04 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '847', 'name' => 'Reklama TIK 08.04 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '848', 'name' => 'Reklama TIK 08.04 #4', 'source_type' => 'facebook'],
            ['campaign_code' => '849', 'name' => 'Wojkowska System 14.04.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '850', 'name' => 'Wojkowska System 14.04.2025 #1 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '851', 'name' => 'Wojkowska System 14.04.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '852', 'name' => 'Wojkowska System 14.04.2025 #2 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '853', 'name' => 'Wojkowska Konkurs 24.04.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '854', 'name' => 'Wojkowska Konkurs 24.04.2025 #1 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '855', 'name' => 'Wojkowska Konkurs 24.04.2025 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '856', 'name' => 'Wojkowska Konkurs 24.04.2025 #2 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '857', 'name' => 'Wojkowska Konkurs 24.04.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '858', 'name' => 'Wojkowska Konkurs 24.04.2025 #3 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '859', 'name' => 'Wojkowska System 14.04.2025 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '860', 'name' => 'Wojkowska System 14.04.2025 #3 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '861', 'name' => 'Wojkowska System 14.04.2025 #4', 'source_type' => 'facebook'],
            ['campaign_code' => '862', 'name' => 'Wojkowska System 14.04.2025 #4 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '863', 'name' => 'Wojkowska System 14.04.2025 #5', 'source_type' => 'facebook'],
            ['campaign_code' => '864', 'name' => 'Wojkowska System 14.04.2025 #5 LP', 'source_type' => 'facebook'],
            ['campaign_code' => '865', 'name' => 'Wojkowska Konkurs 24.04.2025 #4 5 6', 'source_type' => 'facebook'],
            ['campaign_code' => '866', 'name' => 'Reklama TIK 15.04 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '867', 'name' => 'Reklama TIK 15.04 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '868', 'name' => 'Reklama TIK 15.04 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '869', 'name' => 'Dziminiska Doradztwo 13.05', 'source_type' => 'facebook'],
            ['campaign_code' => '870', 'name' => 'Lorens Awans 5.05', 'source_type' => 'facebook'],
            ['campaign_code' => '871', 'name' => 'Reklama TIK 29.04 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '872', 'name' => 'Reklama TIK 29.04 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '873', 'name' => 'Reklama TIK 29.04 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '874', 'name' => 'Wojkowska Konkurs 14.05.2025 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '875', 'name' => 'Reklama tik 6.05 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '876', 'name' => 'Reklama tik 6.05 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '877', 'name' => 'Lorens Czas Pracy 15.05.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '878', 'name' => 'Wojkowska System 15.05.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '879', 'name' => 'Lorens Bezpiecznia wyjścia 14.05.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '880', 'name' => 'Marciniak Jak komunikiwac 27.05.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '881', 'name' => 'Lorens Ocenianie 22.05.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '882', 'name' => 'Wojkowska Podsumowanie 27.05.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '883', 'name' => 'Lorens Awans 29.05.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '884', 'name' => 'Lorens - e-mail dzień przed [Ostania szanda - ]  Ocenianie uczniów w szkole - 2025-05-21 14-03', 'source_type' => 'email'],
            ['campaign_code' => '885', 'name' => 'Lorens Czas pracy 02.06.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '886', 'name' => 'Lorens Podsumowanie 10.06.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '887', 'name' => 'Lorens Rola 05.06.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '888', 'name' => 'Lorena Co Dyrektor 12.06', 'source_type' => 'facebook'],
            ['campaign_code' => '889', 'name' => 'Reklama TIK 10.06 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '890', 'name' => 'Reklama TIK 10.06 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '891', 'name' => 'Lorens Podsumowanie 17.06.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '892', 'name' => 'Reklama TIK 17.06 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '893', 'name' => 'Reklama TIK 17.06 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '894', 'name' => 'Lorens Podsumowanie 25.06.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '895', 'name' => 'Wojkowska Korekty 02.07.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '896', 'name' => 'E-mail do RSP + uczestnicy 26-06-2025 9:05', 'source_type' => 'email'],
            ['campaign_code' => '897', 'name' => 'Lorens Nadzór 01.07.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '898', 'name' => 'Lorens Zaczynasz 03.07.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '899', 'name' => 'Wojkowska Korekty 09.07.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '900', 'name' => 'Wojkowska Korekty 14.07.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '901', 'name' => 'Lorens Kierunki 07.08.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '902', 'name' => 'Wojkowska SIO początkujących 12.08.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '903', 'name' => 'E-mail do RSP + uczestnicy 22-07-2025 12:15', 'source_type' => 'email'],
            ['campaign_code' => '904', 'name' => 'Lorens Zadania 18.08.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '905', 'name' => 'Lorens Kierunki 20.08.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '906', 'name' => 'E-mail do RSP + uczestnicy 13-08-2025 10:55', 'source_type' => 'email'],
            ['campaign_code' => '907', 'name' => 'E-mail do RSP + uczestnicy 13-08-2025 12:15', 'source_type' => 'email'],
            ['campaign_code' => '908', 'name' => 'Lorens Zadania 26.08.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '909', 'name' => 'Wojkowska SIO początkujących 26.08.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '910', 'name' => 'Lorens Komplet 28.08.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '911', 'name' => 'Lorens Awans 04.09.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '912', 'name' => 'Lorens Aspekty 11.09.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '913', 'name' => 'Reklama TIK 02.09 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '914', 'name' => 'Reklama TIK 02.09 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '915', 'name' => 'Reklama TIK 02.09 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '916', 'name' => 'Lorens Zasady 11.09.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '917', 'name' => 'Lorens Zadania 12.09.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '918', 'name' => 'Reklama TIK 09.09 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '919', 'name' => 'Reklama TIK 09.09 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '920', 'name' => 'Wojkowska Prowadzenie 26.09.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '921', 'name' => 'M Rola 24.09.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '922', 'name' => 'L Działalność 17.09.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '923', 'name' => 'L Statut 18.09.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '924', 'name' => 'Reklama TIK 16.09 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '925', 'name' => 'Reklama TIK 16.09 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '926', 'name' => 'Reklama TIK 16.09 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '927', 'name' => 'L Awans 30.09.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '928', 'name' => 'Reklama TIK 23.09 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '929', 'name' => 'Reklama TIK 23.09 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '930', 'name' => 'M Jak 01.10.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '931', 'name' => 'L Ocenianie 02.10.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '932', 'name' => 'L Rozliczanie 09.10.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '933', 'name' => 'Reklama TIK 23.09 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '934', 'name' => 'Reklama TIK 23.09 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '935', 'name' => 'Reklama TIK 23.09 #3', 'source_type' => 'facebook'],
            ['campaign_code' => '936', 'name' => 'W Weryfikacja 30.10.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '937', 'name' => 'K Geogebra 16.10.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '938', 'name' => 'L Rozliczanie 22.10.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '939', 'name' => 'Reklama TIK 17.10 #1', 'source_type' => 'facebook'],
            ['campaign_code' => '940', 'name' => 'Reklama TIK 17.10 #2', 'source_type' => 'facebook'],
            ['campaign_code' => '941', 'name' => 'D Doradztwo 23.10.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '942', 'name' => 'W Rozliczanie 23.10.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '943', 'name' => 'M Jak 06.11.2025', 'source_type' => 'facebook'],
            ['campaign_code' => '944', 'name' => 'L Czas 29.10.2025', 'source_type' => 'facebook'],
        ];

        foreach ($campaigns as $campaign) {
            MarketingCampaign::updateOrCreate(
                ['campaign_code' => $campaign['campaign_code']],
                $campaign
            );
        }
    }
}
